apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bankapp.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}

data:
  MYSQL_HOST: "{{ include "bankapp.fullname" . }}-mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "bankappdb"
  OLLAMA_URL: "http://{{ include "bankapp.fullname" . }}-ollama:11434"
  SERVER_FORWARD_HEADERS_STRATEGY: "native"
