apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bankapp.fullname" . }}-mysql-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}

spec:
  storageClassName: {{ .Values.mysql.persistence.storageClass }}

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bankapp.fullname" . }}-ollama-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}

spec:
  storageClassName: {{ .Values.ollama.persistence.storageClass }}

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.ollama.persistence.size }}
